# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, cmd: str=None):  # noqa: E501
        """Body - a model defined in Swagger

        :param id: The id of this Body.  # noqa: E501
        :type id: str
        :param cmd: The cmd of this Body.  # noqa: E501
        :type cmd: str
        """
        self.swagger_types = {
            'id': str,
            'cmd': str
        }

        self.attribute_map = {
            'id': 'id',
            'cmd': 'cmd'
        }
        self._id = id
        self._cmd = cmd

    @classmethod
    def from_dict(cls, dikt) -> 'Body':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body of this Body.  # noqa: E501
        :rtype: Body
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Body.


        :return: The id of this Body.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Body.


        :param id: The id of this Body.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def cmd(self) -> str:
        """Gets the cmd of this Body.


        :return: The cmd of this Body.
        :rtype: str
        """
        return self._cmd

    @cmd.setter
    def cmd(self, cmd: str):
        """Sets the cmd of this Body.


        :param cmd: The cmd of this Body.
        :type cmd: str
        """

        self._cmd = cmd
