# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.content_type import ContentType  # noqa: F401,E501
from swagger_server import util


class Content(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, text: str=None, type: ContentType=None):  # noqa: E501
        """Content - a model defined in Swagger

        :param text: The text of this Content.  # noqa: E501
        :type text: str
        :param type: The type of this Content.  # noqa: E501
        :type type: ContentType
        """
        self.swagger_types = {
            'text': str,
            'type': ContentType
        }

        self.attribute_map = {
            'text': 'text',
            'type': 'type'
        }
        self._text = text
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'Content':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Content of this Content.  # noqa: E501
        :rtype: Content
        """
        return util.deserialize_model(dikt, cls)

    @property
    def text(self) -> str:
        """Gets the text of this Content.


        :return: The text of this Content.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text: str):
        """Sets the text of this Content.


        :param text: The text of this Content.
        :type text: str
        """
        if text is None:
            raise ValueError("Invalid value for `text`, must not be `None`")  # noqa: E501

        self._text = text

    @property
    def type(self) -> ContentType:
        """Gets the type of this Content.


        :return: The type of this Content.
        :rtype: ContentType
        """
        return self._type

    @type.setter
    def type(self, type: ContentType):
        """Sets the type of this Content.


        :param type: The type of this Content.
        :type type: ContentType
        """

        self._type = type
