# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SignUpRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, username: str=None, password: str=None, email: str=None, remember_me: int=None):  # noqa: E501
        """SignUpRequest - a model defined in Swagger

        :param username: The username of this SignUpRequest.  # noqa: E501
        :type username: str
        :param password: The password of this SignUpRequest.  # noqa: E501
        :type password: str
        :param email: The email of this SignUpRequest.  # noqa: E501
        :type email: str
        :param remember_me: The remember_me of this SignUpRequest.  # noqa: E501
        :type remember_me: int
        """
        self.swagger_types = {
            'username': str,
            'password': str,
            'email': str,
            'remember_me': int
        }

        self.attribute_map = {
            'username': 'username',
            'password': 'password',
            'email': 'email',
            'remember_me': 'rememberMe'
        }
        self._username = username
        self._password = password
        self._email = email
        self._remember_me = remember_me

    @classmethod
    def from_dict(cls, dikt) -> 'SignUpRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SignUpRequest of this SignUpRequest.  # noqa: E501
        :rtype: SignUpRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self) -> str:
        """Gets the username of this SignUpRequest.


        :return: The username of this SignUpRequest.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this SignUpRequest.


        :param username: The username of this SignUpRequest.
        :type username: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    @property
    def password(self) -> str:
        """Gets the password of this SignUpRequest.


        :return: The password of this SignUpRequest.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this SignUpRequest.


        :param password: The password of this SignUpRequest.
        :type password: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    @property
    def email(self) -> str:
        """Gets the email of this SignUpRequest.


        :return: The email of this SignUpRequest.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this SignUpRequest.


        :param email: The email of this SignUpRequest.
        :type email: str
        """

        self._email = email

    @property
    def remember_me(self) -> int:
        """Gets the remember_me of this SignUpRequest.


        :return: The remember_me of this SignUpRequest.
        :rtype: int
        """
        return self._remember_me

    @remember_me.setter
    def remember_me(self, remember_me: int):
        """Sets the remember_me of this SignUpRequest.


        :param remember_me: The remember_me of this SignUpRequest.
        :type remember_me: int
        """

        self._remember_me = remember_me
