# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Vector2i(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, x: int=None, y: int=None):  # noqa: E501
        """Vector2i - a model defined in Swagger

        :param x: The x of this Vector2i.  # noqa: E501
        :type x: int
        :param y: The y of this Vector2i.  # noqa: E501
        :type y: int
        """
        self.swagger_types = {
            'x': int,
            'y': int
        }

        self.attribute_map = {
            'x': 'x',
            'y': 'y'
        }
        self._x = x
        self._y = y

    @classmethod
    def from_dict(cls, dikt) -> 'Vector2i':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Vector2i of this Vector2i.  # noqa: E501
        :rtype: Vector2i
        """
        return util.deserialize_model(dikt, cls)

    @property
    def x(self) -> int:
        """Gets the x of this Vector2i.


        :return: The x of this Vector2i.
        :rtype: int
        """
        return self._x

    @x.setter
    def x(self, x: int):
        """Sets the x of this Vector2i.


        :param x: The x of this Vector2i.
        :type x: int
        """
        if x is None:
            raise ValueError("Invalid value for `x`, must not be `None`")  # noqa: E501

        self._x = x

    @property
    def y(self) -> int:
        """Gets the y of this Vector2i.


        :return: The y of this Vector2i.
        :rtype: int
        """
        return self._y

    @y.setter
    def y(self, y: int):
        """Sets the y of this Vector2i.


        :param y: The y of this Vector2i.
        :type y: int
        """
        if y is None:
            raise ValueError("Invalid value for `y`, must not be `None`")  # noqa: E501

        self._y = y
